INSERT INTO `states` VALUES(1, 'Acre', 'AC', null, null);
INSERT INTO `states` VALUES(2, 'Alagoas', 'AL', null, null);
INSERT INTO `states` VALUES(3, 'Amazonas', 'AM', null, null);
INSERT INTO `states` VALUES(4, 'Amapá', 'AP', null, null);
INSERT INTO `states` VALUES(5, 'Bahia', 'BA', null, null);
INSERT INTO `states` VALUES(6, 'Ceará', 'CE', null, null);
INSERT INTO `states` VALUES(7, 'Distrito Federal', 'DF', null, null);
INSERT INTO `states` VALUES(8, 'Espírito Santo', 'ES', null, null);
INSERT INTO `states` VALUES(9, 'Goiás', 'GO', null, null);
INSERT INTO `states` VALUES(10, 'Maranhão', 'MA', null, null);
INSERT INTO `states` VALUES(11, 'Minas Gerais', 'MG', null, null);
INSERT INTO `states` VALUES(12, 'Mato Grosso do Sul', 'MS', null, null);
INSERT INTO `states` VALUES(13, 'Mato Grosso', 'MT', null, null);
INSERT INTO `states` VALUES(14, 'Pará', 'PA', null, null);
INSERT INTO `states` VALUES(15, 'Paraíba', 'PB', null, null);
INSERT INTO `states` VALUES(16, 'Pernambuco', 'PE', null, null);
INSERT INTO `states` VALUES(17, 'Piauí', 'PI', null, null);
INSERT INTO `states` VALUES(18, 'Paraná', 'PR', null, null);
INSERT INTO `states` VALUES(19, 'Rio de Janeiro', 'RJ', null, null);
INSERT INTO `states` VALUES(20, 'Rio Grande do Norte', 'RN', null, null);
INSERT INTO `states` VALUES(21, 'Rondônia', 'RO', null, null);
INSERT INTO `states` VALUES(22, 'Roraima', 'RR', null, null);
INSERT INTO `states` VALUES(23, 'Rio Grande do Sul', 'RS', null, null);
INSERT INTO `states` VALUES(24, 'Santa Catarina', 'SC', null, null);
INSERT INTO `states` VALUES(25, 'Sergipe', 'SE', null, null);
INSERT INTO `states` VALUES(26, 'São Paulo', 'SP', null, null);
INSERT INTO `states` VALUES(27, 'Tocantins', 'TO', null, null);